### ISSUE TITLE
dependencies file

### ISSUE THREAD

**Issue by rootsmusic** [IBM/snapml-docs#29]
I'm looking for the package's dependency file.  (A folder has a [requirements.txt](https://github.com/IBM/snapml-docs/blob/main/docs/requirements.txt), but I assume that's for the docs.  [snapml-examples](https://github.com/IBM/snapml-examples) has 2 dependency files, but I assume those files are to run the examples.)

**Comment by tdoublep** [comment]
Snap ML source code is not open-source, so what you are looking for doesn't exist exactly. You can inspect the dependencies either by installing Snap ML in a clean conda (or pyenv environment) as seeing what pip pulls in. Alternatively, you can unzip one of the wheels that we distribute and inspect the METADATA file which contains the dependencies as below:
```
Requires-Dist: scikit-learn
Requires-Dist: scipy
Requires-Dist: numpy >=1.18.5 ; python_version < "3.10"
Requires-Dist: numpy >=1.21.3 ; python_version == "3.10"
Requires-Dist: numpy >=1.23.2 ; python_version == "3.11"
```
